import Header from "@/components/header/Header";

export const metadata = {
    title: "Portfolio - tools",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <>
            <header>
                <Header anotherPage />
            </header>
            {children}
        </>
    );
}
